name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - ".gitignore"
      - "renovate.json"
      - ".release-please-config.json"
      - "release-please-config.json"
      - "oscal-component.yaml"
      - "CODEOWNERS"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "SECURITY.md"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-test:
    name: ${{ matrix.type }} ${{ matrix.flavor }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        flavor: [upstream, registry1]
        type: [install, upgrade]

    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        uses: defenseunicorns/uds-common/.github/actions/test@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0
        with:
          flavor: ${{ matrix.flavor }}
          type: ${{ matrix.type }}

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@f0164622ffc2007e96a0e1deaa3f5064db04b148 # v1.1.0
        with:
          suffix: ${{ matrix.type }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
